# Function Section

# Question 1
Write a function wordcount that takes a string as input, and outputs the word-count. The function should ignore any punctuation and capitalisation. Also, any numbers should be counted as a token-word "NUMBER".

Example:
>>> wordcount('This is a test. There are 14 words and 2 sentences in this test!')
{'this': 2, 'is': 1, 'a': 1, 'test': 2, 'there': 1, 'are': 1, 'NUMBER': 2, 'words': 1, 'and': 1, 'sentences': 1, 'in': 1}



In [ ]:
import re
def word_count(str):
    counts = dict()
    words = str.split()
    Length = len(re.findall("[a-zA-Z_]+", str))
    print("Length of the word is:", Length)  
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1

    return counts

print(word_count('This is a test. There are 14 words and 2 sentences in this test!'))

Length of the word is: 12
{'This': 1, 'is': 1, 'a': 1, 'test.': 1, 'There': 1, 'are': 1, '14': 1, 'words': 1, 'and': 1, '2': 1, 'sentences': 1, 'in': 1, 'this': 1, 'test!': 1}


# Question 2
Write a function wordsearch that takes two arguments:
- a list of strings
- a one-word string
and outputs the string which contains the maximum number of occurences of the word (ignoring punctuation and capitalisation)
Example:
>>> wordsearch(['Sentence 1', 'This is sentence number 2.', 'Sentence 3: one more sentence.'], 'sentence')
'Sentence 3: one more sentence.'

# Pandas Section


In [ ]:
#question 1 : show common values from two arrays
#question 2 compare two array and remove the repative array in a
#ques 3,  remove dupicates from column 1 and show only first occurances

In [ ]:
import numpy as np
import pandas as pd

a = np.array([1,2,3,4,5])
b = np.array([2,3,6,7,8])

In [ ]:
#question 1 : show common values
import numpy as np
import pandas as pd

a = np.array([1,2,3,4,5])
b = np.array([2,3,6,7,8])
print(np.intersect1d(a,b))

[2 3]


In [ ]:
#question 2 compare two array and remove the repative array in a
import numpy as np
import pandas as pd

a = np.array([1,2,3,4,5])
b = np.array([2,3,6,7,8])
difference = np.setdiff1d(a,b)
print(difference)



[1 4 5]


In [ ]:
#ques 3,  remove dupicates from column 2 and show only first occurances
import numpy as np
import pandas as pd

a = np.array([1,2,3,4,5])
b = np.array([2,3,6,7,8])

new_array = np.array([a,b])
print(new_array)
print("")

unique_arr = np.unique(new_array)
print(unique_arr)


[[1 2 3 4 5]
 [2 3 6 7 8]]

[1 2 3 4 5 6 7 8]


# Question 1
Load purchase data and price data from purchases.csv and prices.csv

In [152]:
import pandas as pd
prices = pd.read_csv('/content/prices.csv')
purchases = pd.read_csv('/content/purchases.csv') 
#print(prices )
#print("")
#print(purchases )
#print("")

output1 = pd.merge(prices , purchases , 
                   on='Product', 
                   how='inner')
output1['Purchase date'] = pd.to_datetime(output1['Purchase date'].astype('str'), format = '%Y%m%d')
output1['total_sale']=output1['Quantity_purchased']*output1['Price']
# displaying result

output1.to_csv( "output1.csv", index=False, encoding='utf-8-sig')
print(output1)

            Product  Price  ... Quantity_purchased total_sale
0     Chocolate bar    0.5  ...                  2        1.0
1     Chocolate bar    0.5  ...                  1        0.5
2     Chocolate bar    0.5  ...                  1        0.5
3     Chocolate bar    0.5  ...                  3        1.5
4     Chocolate bar    0.5  ...                  1        0.5
5     Chocolate bar    0.5  ...                  3        1.5
6     Chocolate bar    0.5  ...                  3        1.5
7     Chocolate bar    0.5  ...                  3        1.5
8            Coffee    2.0  ...                  3        6.0
9            Coffee    2.0  ...                  2        4.0
10           Coffee    2.0  ...                  3        6.0
11           Coffee    2.0  ...                  2        4.0
12           Coffee    2.0  ...                  2        4.0
13           Coffee    2.0  ...                  2        4.0
14           Coffee    2.0  ...                  1        2.0
15      

# Question 2
Calculate who has bought the largest number of drinks IN TOTAL (across all their several purchases, note there is a Quantity column) and how many drinks he/she has purchased

In [167]:
import pandas as pd
import numpy as np
output1 = pd.read_csv("output1.csv")

#to print all values of drink category
options = ['Drink'] 
drink_cat = output1[output1['Product'].isin(options)] 
print(drink_cat)

# customers with largest number of drinks 
drink_count = drink_cat.groupby(['Product','Customer'])['Quantity_purchased'].sum().sort_values()
print(drink_count)

   Product  Price Customer Purchase date  Quantity_purchased  total_sale
22   Drink    1.0    Carol    2018-05-04                   1         1.0
23   Drink    1.0    Frank    2018-05-23                   2         2.0
24   Drink    1.0    Carol    2018-05-18                   3         3.0
25   Drink    1.0    Frank    2018-06-22                   1         1.0
26   Drink    1.0    Frank    2018-05-01                   3         3.0
27   Drink    1.0    Carol    2018-05-21                   1         1.0
28   Drink    1.0      Bob    2018-05-27                   1         1.0
29   Drink    1.0    Carol    2018-05-29                   1         1.0
30   Drink    1.0    Frank    2018-05-29                   2         2.0
31   Drink    1.0    Alice    2018-06-03                   3         3.0
Customer
Bob      1
Alice    3
Carol    6
Frank    8
Name: Quantity_purchased, dtype: int64


# Question 3
Calculate the total sales in GBP of all types of sandwiches, summarised per month

In [225]:

import pandas as pd
import dateutil
output1 = pd.read_csv("output1.csv")
#print(output1)

output1['month'] = output1['Purchase date'].values.astype('datetime64[M]')
sandwich_cat =output1[output1.Product.str.contains("sandwich")]
#print(sandwich_cat)
sales = sandwich_cat.groupby(['month'])[['total_sale']].sum().reset_index()
#sales.head()
print(sales)



       month  total_sale
0 2018-05-01        77.0
1 2018-06-01        91.5


# Numpy Section
M = np.array([[1, 5, 1], [10, 7, 1.5], [6.9, 5, 1], [19, 9, 100], [11, 11, 11]])

# Question 1
Filter M to only keep rows where the maximum value is >= 10

In [ ]:
import numpy as np

M = np.array([[1, 5, 1], [10, 7, 1.5], [6.9, 5, 1], [19, 9, 100], [11, 11, 11]],dtype='int16')

new_arr = M[M> 10]

print(new_arr)

[ 19 100  11  11  11]


# Question 2
Sort the columns of M based on the mean of each column (largest first)

# New Section

In [ ]:
M = np.array([[1, 5, 1], 
              [10, 7, 1.5],
              [6.9, 5, 1], 
              [19, 9, 100],
              [11, 11, 11]])


mean = -np.sort(np.mean(-M,axis=0))
print(mean)



[22.9   9.58  7.4 ]
